language/language/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/',include('main.urls',namespace='main')),
    url(r'^wiki/',include('wiki.urls', namespace='wiki')),
    url(r'^.*',include('main.urls')),
]

language/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$',views.main,name='main'),
]

language/wiki/urls.py
from django.conf.urls import url
from wiki import views

urlpatterns = [
    url(r'^about/$', views.about, name='about'),
    url(r'^$', views.wiki, name='wiki'),
    url(r'^category/(?P<categoryID>[\w\-]+)/$', views.category, name='category'),
    url(r'^addCategory/$', views.addCategory, name='addCategory'), 
    url(r'^addPage/(?P<categoryID>[\w\-]+)/$', views.addPage, name='addPage'),
    url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory,
 name='deleteCategory'),
    url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage,
 name='deletePage'),
    url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory,
 name='updateCategory'),
    url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage,
 name='updatePage'),
]

language/wiki/models.py
import random
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
        name = models.CharField(max_length=128, unique=True)
        views = models.IntegerField(default=0)
        likes = models.IntegerField(default=0)
        
        def save(self, *args, **kwargs):
            self.name = self.name.replace(' ', '-')
            super(Category, self).save(*args, **kwargs)
         
        def __str__(self):
            return self.name
     
     
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def save(self, *args, **kwargs):
        self.title = self.title.replace(' ', '-')
        super(Page, self).save(*args, **kwargs)
                     
                     
    def __str__(self):
        return self.title

language/wiki/forms.py
from django import forms
from wiki.models import Category, Page

class NameForm(forms.Form):
    name = forms.CharField(max_length=100, label='姓名')
 
class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label='類別名稱', help_text='請輸入類別名稱')
    
    class Meta:
        model = Category
        fields = ('name', )
        
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='頁面標題', help_text='請輸入頁面標題')
    url = forms.URLField(max_length=128, label='頁面網址', help_text='請輸入頁面網址')
        
    class Meta:
        model = Page
        exclude = ('category', 'views')
            
    def clean(self):
        cleanedData = self.cleaned_data
        url = cleanedData.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleanedData['url'] = url
        return cleanedData

language/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    now = datetime.datetime.now()
    context = {'message':'Django 很棒','time':now}
    return render(request, 'main/main.html', context)

language/wiki/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from wiki.models import Category, Page
from wiki.forms import CategoryForm, PageForm

def wiki(request):
    categories = Category.objects.order_by('-likes')
    context = {'categories':categories}
    return render(request, 'wiki/wiki.html',context)

def about(request):
    return render(request, 'wiki/about.html')

def category(request, categoryID):
    context = {}
    try:
        category = Category.objects.get(id=categoryID)
        context['category'] = category
        context['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
        pass
    return render(request, 'wiki/category.html', context)

def addCategory(request):
    template = 'wiki/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    # request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('wiki:wiki'))
    # Or try this: return wiki(request) 
    
def addPage(request, categoryID):
    template = 'wiki/addPage.html'
    try:
        pageCategory = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return category(request, categoryID)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('wiki:category', args=(categoryID, )))

def deleteCategory(request, categoryID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('wiki:wiki'))

def deletePage(request, pageID):
    if request.method!='POST':
        return wiki(request)    
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryID = pageToDelete.category.id
        pageToDelete.delete()
    else:
        categoryID = ''
    return redirect(reverse('wiki:category', args=(categoryID, )))

def updateCategory(request, categoryID):
    template = 'wiki/updateCategory.html'
    try:
        category = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return wiki(request)
    if request.method=='GET':
        form = CategoryForm(instance=category)
        return render(request, template, {'form':form, 'category':category})
    # request.method=='POST'
    form = CategoryForm(request.POST, instance=category)
    if not form.is_valid():
        return render(request, template, {'form':form, 'category':category})
    form.save()
    return redirect(reverse('wiki:wiki'))

def updatePage(request, pageID):
    template = 'wiki/updatePage.html'
    try:
        page = Page.objects.get(id=pageID)
    except Page.DoesNotExist:
        return category(request, '')
    if request.method=='GET':
        form = PageForm(instance=page)
        return render(request, template, {'form':form, 'page':page})
    # request.method=='POST'
    form = PageForm(request.POST, instance=page)
    if not form.is_valid():
        return render(request, template, {'form':form, 'page':page})
    form.save()
    return redirect(reverse('wiki:category', args=(page.category.id,)))

language/main/templates/main/main.html
<!doctype html>
{% load staticfiles %} 
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>Django 說--Hello world!</h1>
<p>{{message}}</p>
<p>now time:<span style=color:red;>{{time}}</span>span></p>
<a href={% url 'wiki:wiki' %}>关于程式语言</a>
<a href={% url 'wiki:about' %}>about</a>
</body>
</html>

language/wiki/templates/wiki/about.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<p>这里是程式语言小百科，欢迎浏览
<a href={% url 'main:main' %}>HOME</a> 
</body>
</html>

language/wiki/templates/wiki/addCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>新增一個程式語言分類</h1>
<form method=post action={% url 'wiki:addCategory' %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 頁面</a></p>
</body>
</html>

language/wiki/templates/wiki/addPage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>


<h1>在"{{category.name}}"分類中新增一筆網頁</h1>
<form method=post action={% url 'wiki:addPage' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<p><a href={% url 'wiki:category' category.id %}>回{{category.name}}網頁</a></p>

</body>
</html>

language/wiki/templates/wiki/category.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href="{% static 'main/css/main.css' %}">
</head>
<body>

{% if category %}
  <h1>{{category.name}}</h1>
  {% if pages %}
    <table>
      <tr><th>頁面標題</th></tr>
      {% for page in pages %}
        <tr>
         <td>
           <a href={{page.url}}>{{page.title}}</a>
         </td>
         <td>
          <form action={% url 'wiki:updatePage' page.id %}>
           <input type=submit value=修改>
          </form>
         </td>
         <td>
           <form method=post action={% url 'wiki:deletePage' page.id %}>
             {% csrf_token %}
             <input type=submit value=刪除>
           </form>
          </td> 
         </tr>
      {% endfor %}
    </ul>
  {% else %}
    <p><strong>此類別目前並無頁面。</strong></p>
  {% endif %}
  <p><a href={% url 'wiki:addPage' category.id %}>新增頁面</a></p>
{% else %}
  <p>所指定的類別「{{categoryName}}」不存在。</p>
{% endif %}
<p><a href={% url 'wiki:wiki' %}>回 Wiki 頁面</a></p>
<body>
<html>

language/wiki/templates/wiki/updateCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>

<h1>修改程式語言分類</h1>
<form method=post action={% url 'wiki:updateCategory' category.id %}>
  {% csrf_token %}
  {{form.as_p}}
  <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 網頁</a></p>

</body>
</html>

language/wiki/templates/wiki/updatePage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<!-- 一再撰寫相同的 HTML 標頭資料，有沒有人開始覺得很煩了？？ -->
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>

<h1>修改網頁</h1>
<form method=post action={% url 'wiki:updatePage' page.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' page.category.id %}>回「{{page.category.name}}」網頁
</a></p>

</body>
</html>

language/wiki/templates/wiki/wiki.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>Wiki 說--Hello world!</h1>
{% if categories %}
  <h2>程式語言分類：</h2>
  <table>
   <tr><th>分類名稱</th><th></th><th></th></tr>
    {% for category in categories %}
     <tr>
      <td>
       <a href={% url 'wiki:category' category.id %}>{{category.name}}</a>
      </td>
      <td>
       <form action={% url 'wiki:updateCategory' category.id %}>
         <input type="submit" value=修改>
       </form>
      </td>
      <td>
       <form method=post action={% url 'wiki:deleteCategory' category.id %}>
         {% csrf_token %}
         <input type=submit value=刪除>
        </form>
       </td>
      </tr>
    {% endfor %}
  </ul>
{% else %}
  <p><strong>目前尚未設定程式語言類別。</strong></p>
{% endif %}
<p><a href={% url 'wiki:addCategory' %}>新增程式語言分類</a></p>
<a href={% url 'main:main' %}>HOME</a> 
</body>
</html>